### ISSUE TITLE
Stronger users passwords

### ISSUE THREAD

**Issue by D3ryk** [sparkoo/speakup#19]
Make  rule which will allow to registrate only users which will choose some stronger password.

Password criteriums:

* at least 8 character long.
* containst at least one upper case.
* contains at least one digit.

**Comment by sparkoo** [comment]
I would make it minimum of 8 characters -> http://random-ize.com/how-long-to-hack-pass/

**Comment by D3ryk** [comment]
Check https://docs.jboss.org/hibernate/validator/5.0/reference/en-US/html/validator-customconstraints.html#validator-customconstraints-validator
